title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/minima"
twitter_username: jekyllrb
github_username:  jekyll

# Basic i18n - if you change the lang parameter,
# minima will try to use the strings in _data/locales/[lang].yml
lang: en

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
