title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/minima"
twitter_username: jekyllrb
github_username:  jekyll

### Basic localisation (l10n)
# If you customize the lang parameter, minima will try to use the strings in _data/locales/[lang].yml
# Read https://github.com/jekyll/minima/README.md for more information.
#lang: fr

# Even the day and month names will be translated. You can customize your date by
# uncommenting the following line and customizing the date format:
#date_format: "Le %-d %B %Y"

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
