title: Java developer blog
author: Vlasov Maksim
email: maks.mephi@gmail.com
description: ""
baseurl: ""
#twitter_username: jekyllrb
github_username:  vmaks

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

disqus:
    shortname: https-vmaks-github-io

google_analytics: UA-85794354-1
