title: C++ developer blog
author: Vlasov Maksim
email: maks.mephi@gmail.com
description: ""
baseurl: ""
#twitter_username: jekyllrb
github_username:  vmaks
disqus:
	shortname: https-vmaks-github-io
google_analytics: UA-85794354-1

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

