---
title: JNX.wales
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  uploads:
    title: Uploads
    output: true
  pages:
    title: Pages
    output: true
defaults:
- scope:
    path: ''
    type: products
  values:
    layout: product
    welsh: ''
    image: ''
    short: ''
- scope:
    path: ''
    type: pages
  values:
    welsh: ''
    layout: page
author:
  name: Jake Jenkins
  email: dev@jnx.wales
description: 'We are a small Web Design and Web Application company based in south Wales that make awesome websites and business apps.'
show_excerpts: false
minima:
  date_format: "%-d %b, %Y"
  social_links:
    twitter: jakejnx
    github: jakejnx
theme: minima
plugins:
- jekyll-seo-tag
