title: wazza's blog
author:
  name: Vidur
  email: vidur.p11@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Musings of a nerd

show_excerpts: true # set to true to show excerpts on the homepage
excerpt_separator: <!--more-->

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: dark
  # generate social links in footer
  social_links:
    #twitter: jekyllrb
    github:  MeanManMachineMan
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: vidur-pherwani-b146b3179
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
#  - about.md

# Build settings
theme: minima
url: "https://meanmanmachineman.github.io/"
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

google_analytics: G-5DNSJRFB7G